package scripts

import (
	"fmt"
	"strings"
)

// generateUnixScript generates a Unix shell script
func generateUnixScript(javaPath, jarPath, xms, xmx string, jvmFlags []string) string {
	// Build JVM flags string
	flagsStr := strings.Join(jvmFlags, " ")

	script := fmt.Sprintf(`#!/bin/bash
# Generated by mcinit
# Minecraft Server Startup Script

# Change to script directory
cd "$(dirname "$0")"

# Java executable
JAVA="%s"

# Server jar
JAR="%s"

# JVM Memory settings
XMS="%s"
XMX="%s"

# JVM Flags
JVM_FLAGS="%s"

# Start server
echo "Starting Minecraft server..."
exec "$JAVA" $JVM_FLAGS -jar "$JAR" nogui
`, javaPath, jarPath, xms, xmx, flagsStr)

	return script
}

