package scripts

import (
	"fmt"
	"strings"
)

// generateWindowsPowerShellScript generates a PowerShell script
func generateWindowsPowerShellScript(javaPath, jarPath, xms, xmx string, jvmFlags []string) string {
	// Build JVM flags string
	flagsStr := strings.Join(jvmFlags, " ")

	script := fmt.Sprintf(`# Generated by mcinit
# Minecraft Server Startup Script

# Change to script directory
Set-Location $PSScriptRoot

# Java executable
$JAVA = "%s"

# Server jar
$JAR = "%s"

# JVM Memory settings
$XMS = "%s"
$XMX = "%s"

# JVM Flags
$JVM_FLAGS = "%s"

# Start server
Write-Host "Starting Minecraft server..."
& $JAVA $JVM_FLAGS.Split(" ") -jar $JAR nogui
`, javaPath, jarPath, xms, xmx, flagsStr)

	return script
}

// generateWindowsCMDScript generates a CMD batch script
func generateWindowsCMDScript(javaPath, jarPath, xms, xmx string, jvmFlags []string) string {
	// Build JVM flags string
	flagsStr := strings.Join(jvmFlags, " ")

	script := fmt.Sprintf(`@echo off
REM Generated by mcinit
REM Minecraft Server Startup Script

REM Change to script directory
cd /d %%~dp0

REM Java executable
set JAVA=%s

REM Server jar
set JAR=%s

REM JVM Memory settings
set XMS=%s
set XMX=%s

REM JVM Flags
set JVM_FLAGS=%s

REM Start server
echo Starting Minecraft server...
"%%JAVA%%" %%JVM_FLAGS%% -jar "%%JAR%%" nogui
pause
`, javaPath, jarPath, xms, xmx, flagsStr)

	return script
}

